Feature/react-query
davidbtorres/ecommerce-app pull request #4
Opened 2023-08-08 02:36 UTC by davidbtorres

All ky.gets are now wrapped in react-query/tanstack-query custom hooks and all state logic based around fetched data has been replaced with useQuery hooks. 

Please let me know if I missed anything, thanks!

2023-08-08 14:35 UTC, Idonoghue reviewed
Very clean, simple approach to implementation! I did suggest making it a bit more complicated just to learn a useful pattern when using React-Query on a larger codebase

2023-08-08 14:35 UTC, Idonoghue commented on src/components/Categories.tsx
> +  const productsQuery = useQuery('products', fetchProducts)
Very nice! The cool thing about the hooks approach is how easy it is to abstract these into reusable custom hooks. 

It's incredibly common to need to call the same API endpoint in different components. Also moving your API calling logic into a hook hides implementation details from components.
```suggestion
  const categoriesQuery = useCategoriesQuery()
  const productsQuery = useProductsQuery()
```

These hooks can basically be a thin wrapper around the useQuery hook just with the QueryKey & async function defined.

2023-08-08 14:35 UTC, Idonoghue commented on src/components/ProductPage.tsx
> +  const productQuery = useQuery('product', fetchProduct)
Here's an example of a custom hook where we can pass in the needed data to make the API call. Also React-Router has useful hooks to extract variables from the url
```suggestion
  const { productId } = useParams()
  
  const productQuery = useProductQuery({ productId })
```

2023-08-09 03:31 UTC, davidbtorres commented
I refactored the useQuery calls into 3 individual custom hooks, it has moved a lot of fetch logic out of my components - definitely worth learning! Please let me know if it all looks correct, thanks again!

2023-08-09 14:06 UTC, Idonoghue requested changes
Great refactor! Just had some minor things

2023-08-09 14:06 UTC, Idonoghue commented on src/hooks/useCategoriesQuery.tsx
> +}
Really nice job! As you can see there is still some repetitive code as each of these hooks are almost identical with slight differences for the data type & url they're calling. 

Since we have dozens maybe even hundreds of different queries we use a higher order function for this in ADDI. We can pass in the differences to the first function like the data type as a generic `T`, the url, & the query key and it returns this function that calls useQuery. 

Obviously this is super overkill here but wanted to highlight some things we did to evolve beyond this pattern as the code base grew.

2023-08-09 14:06 UTC, Idonoghue commented on src/pages/Product.tsx
> +  const productQuery = productId ? useProductQuery(productId) : null
We can never call hooks conditionally. React is letting this slip by because productId is always defined when this renders. However we can rewrite this to always call the hook by moving this conditional to occur inside of `useProductQuery`
```suggestion
  useProductQuery(productId)
```

2023-08-09 14:06 UTC, Idonoghue commented on src/hooks/useProductQuery.tsx
> +function useProductQuery(productId: string) {
```suggestion
function useProductQuery(productId: string | undefined) {
```

2023-08-09 14:06 UTC, Idonoghue commented on src/hooks/useProductQuery.tsx
> +  })
To make sure we only call the query when productId is defined `useQuery` as a super helpful `enabled` property
```suggestion
  }, { enabled: !!productId })
```

2023-08-09 23:52 UTC, davidbtorres commented on src/pages/Product.tsx
> +  const productQuery = productId ? useProductQuery(productId) : null
Ah I like this much better!

2023-08-10 00:01 UTC, davidbtorres commented
HOC for custom useQuery hooks added to remove repetitive code, each custom hook definition now only contains their unique arguments i.e. the type, key, and url.

2023-08-10 00:02 UTC, Idonoghue reviewed
Wow you eager beaver!

2023-08-10 00:02 UTC, Idonoghue commented on src/hooks/useProductQuery.tsx
> +    `product-${productId}`,
I think it's just a better standard to have array query keys. Allows you to potentially do things like invalidate all caches of product queries  
```suggestion
    ['product', productId],
```

2023-08-10 00:02 UTC, Idonoghue commented on src/hooks/withQuery.tsx
> +  queryKey: string,
ReactQuery exposes a QueryKey type
```suggestion
  queryKey: QueryKey,
```

2023-08-10 00:02 UTC, Idonoghue commented on src/hooks/withQuery.tsx
> +    options
Here we can add our useful logic to perhaps not run a query unless every value in the key is defined
```suggestion
   { enabled: !Array.isArray(queryKey) || queryKey.every(isPresent), ...(options || {}) }
```

2023-08-10 00:23 UTC, davidbtorres commented
Let me know how it looks! 🦫

2023-08-10 04:11 UTC, Idonoghue approved these changes
🙌

2023-08-11 02:56 UTC, merged